<?php
return array(
    'index'=> array(
        'heading1' => 'Reckon',
    'heading2'=> 'Business Advisories',
    'paragraph'=>'Maintaining an accurate accounting record is critical part of any business, so the success of your business depends on those records. Accounting records help you evaluate your business performance by identifying any weakness in the operation this allowing you to take timely corrective action. Owning and operating your own business requires you to perform many tasks to keep your business operating well. While you need to stay involved in many of the day-to-day responsibilities of your business, it can be advantageous to outsource the accounting and bookkeeping work to experts.',
    'read_more'=>'Read More',
    'services'=>'Services'),
    'aboutus'=>array('paragraph'=>'Reckon specializes in bookkeeping services for small and medium size businesses in Kuwait market. Whether you are launching business or already run an established business, we at Reckon can provide you with efficient bookkeeping services. Our services will help you reduce costs and manage your business efficiently. We at Reckon provide you with easy access to qualified professionals such as (CPA, CMA, CIA, CISA, CFC, CIPA, ICVS, CCGO, CIB). We at Reckon provide you with accounting and bookkeeping services using financial accounting system.','manager_name'=>'Mohammad Al-Sabea','manager_text'=>'General Manager at Reckon','background'=>'Background','background_text'=>'Mohammad has more than 20 years of working experience in Accounting, Auditing and Risk Management at several industries including Banking, Petrochemical, Investment and Telecommunications. Mohammad holds the CPA, CIA, CISA, CCGO and CIB professional certifications.','contact'=>'Contact Info.','contact_text'=>'(+965) 50009777 - M.ALSABEA@KW-RECKON.COM '),
    'contactus'=>array('name'=>'Name','email'=>'Email','phone'=>'Phone Number','message'=>'Message','send_message'=>'Send Message'),
    'services'=>array('bookkeeping'=>'Bookkeeping And Accounting Management Services','financial_analysis'=>'Financial Analysis Services','financial_planning'=>'Financial Planning Services','feasibility_study'=>'Feasibility Studies Services','cfo'=>'CFO Services'),
    'header'=>array('home'=>'Home','about'=>'About Us','services'=>'Services','contact'=>'Contact Us','arabic'=>'العربية','english'=>'English','bookkeeping'=>'Bookkeeping','financial_analysis'=>'Financial Analysis','financial_planning'=>'Financial Planning','feasibility_study'=>'Feasibility Studies','cfo'=>'CFO Services','working_hours'=>'Working Hours: Mon - Fri: 8:30 - 18:30','email'=>'Send us a Email','question'=>'Have any question?'),
    'bookkeeping_service'=>array('paragraph'=>'Whether you are launching a startup of small business or already run an established business, Reckon can offer you a convenient bookkeeping solution. We provide you with easy access to qualified accounting professionals without you ever having to hire them. Even if you own an established business and your in-house bookkeeper is not sufficiently qualified or is unable to keep pace with the work flow, we can provide efficient bookkeeping solutions at cost-effective rates.','list1'=>'Accounts Payable Management (Vendor Bills and Payments)','list2'=>'Accounts Receivable Management (Customer Invoices and Collections)','list3'=>'Bank Reconciliations','list4'=>'Revenue Reconciliation with Bank Deposits','list5'=>'Preparing Chart of Accounts','list6'=>'Fixed Assets','list7'=>'General Ledger','list8'=>'Help in creating accounting procedures','list9'=>'Working with Professionals (External Auditor, Banker, Attorney etc.)','list10'=>'Preparing Financial Statements','list11'=>' Preparing Adjusted Trial Balance'),
    'financial_analysis_service'=>array('paragraph1'=>'Financial Ratios Analysis is a way of determining the health of a business. Just as a doctor might take your pulse, temperature and blood pressure to give information on your health, we use Financial Ratios Analysis to identify weaknesses of your business.','paragraph2'=>'Financial Ratios Analysis is an important tool for small business owners to measure progress toward reaching their business goals, as well as toward competing in the market. Financial Ratios Analysis is a useful tool that will provide key indicators of your business performance. Business owners use Financial Ratios Analysis to identify weaknesses from which corrective action can be taken.','paragraph3'=>'The ratios presented below represent some of the standard ratios used in business practice. We can also develop your own ratios and indicators based on what you consider important and meaningful to your business and industry:','list1'=>'Operational Efficiency Ratios - How efficiently are you utilizing your assets and managing your liabilities?','list2'=>'Profitability Ratios - How well is your business performing over a specific period?','list3'=>'Liquidity Ratios - Does your business have enough cash on an ongoing basis to meet its operational obligations?'),
    'financial_planning_service'=>array('paragraph1'=>'Financial planning is at the heart of every successful business. A financial plan, which includes detailed financial statements and projections, forms the core of your overall business plan. Your business will only be as strong as its financial plan.','paragraph2'=>'We will develop your business financial plan to help you build a stronger financial position. Developing your business financial plan can also help you strengthen your business operation.','paragraph3'=>'Our financial planners will work closely with you to understand your objectives while reviewing all of your options thoroughly. We simplify the process and work as your partner to develop your financial plan. With valued advice and an expert’s touch, we can help you reach your business goals.','paragraph4'=>'Your financial plan will include:','list1'=>'Start-up costs, if you are starting a new business','list2'=>'Cash flow projections','list3'=>'Projected balance sheets and income statements','list4'=>'A break-even analysis'),
    'feasibility_study_service'=>array('paragraph1'=>'The feasibility study focuses on helping answer the essential question of “should we proceed with the proposed project idea?” All activities of the study are directed toward helping answer this question.','paragraph2'=>'Feasibility studies is an analysis and evaluation of your proposed project to determine if it is technically feasible, is feasible within the estimated cost, and will be profitable.','paragraph3'=>'Reckon deploys three main components for feasibility studies:','list1'=>'Market Analysis: This includes a study of the industry, present market, projected market potential, sales, competition, and potential buyers. Understanding market potential gives businesses insight into the demand for their product or service.','list2'=>'Financial Analysis: It establishes how much start-up capital is required, sources of capital, returns on investments, and other financial estimates such as gross profit margins and net income.','list3'=>'Technical Analysis: It analyses the materials, transportation, labor, location, technology required, and other factors related to the product or service.'),
    'cfo_service'=>array('paragraph1'=>'Successful business owners are expected to take critical decisions directly impacting the success of the business. Growth initiatives, resource allocation, cost management, cash-flow management, all of this is a daunting task.','paragraph2'=>'With such a broad scope of responsibility and increased complexity in navigating today’s business environment, business owners call Reckon when they need independent advice from professionals who understand these challenges, having faced them and implemented, first-hand, solutions to similar problems. At Reckon, we have assembled a team of expertise, CFOs and others experienced in finance operations to provide objective guidance for critical decisions impacting business.','paragraph3'=>'Business Owners calls us when :','list1'=>'They have never had a formal strategic planning process and need assistance in facilitating the process with the business owner.','list2'=>'They have multiple, uncoordinated business initiatives and want an objective opinion about how to manage them.','list3'=>'They are experiencing liquidity risks and would like guidance to better manage cash flow and working capital.','list4'=>'They suspect fraud and/or embezzlement due to accounting irregularities and want to understand the steps they need to take to prove or disprove their suspicions.','list5'=>'They want to understand what benchmarks and metrics are available and relevant for measuring performance against their peers.','list6'=>'They need improvement in finance and accounting processes such as level of automation, degree of standardization, cycle times and quality and controls.','list7'=>'They are considering functional organization shifts or different operating models to improve the delivery of services and products or reduce the expenditure.','list8'=>'They are implementing fundamental structural change in the business due to a merger, acquisition, joint venture or other legal entity change.','list9'=>'They have identified weaknesses in their internal controls.'), 
      );








